# Site settings
baseURL = "https://kumarwrites.com/"
languageCode = "en-us"
title = "Kumar Garapati's Writings"
theme="story"
paginate = 5
buildFuture = true

[[menu.social]]
  name = "GitHub"
  title = "fab fa-github-square"
  url = "https://github.com/kumaro/"

[[menu.main]]
  name = "Archives"
  title = "Archives"
  url = "/posts/"

[params]
  author = "Kumar Garapati"
  twitter = "Kumar_Garapati"
  classes = []

[outputs]
  home = ["HTML", "JSON", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML", "RSS"]